In [1]:
from FamaData import FamaData
import pandas as pd

In [2]:
fd = FamaData('data/')

In [3]:
fd.get_net_share_issue_data()

,< 0,ZERO,Lo 20,Qnt 2,Qnt 3,Qnt 4,Hi 20,Lo 10,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Hi 10,caldt
0,0.54,0.26,-0.35,0.52,-0.52,0.07,0.02,-1.14,0.75,1.47,-1.40,-1.23,0.61,-0.60,0.84,-0.13,0.95,1963-07-31
1,5.52,4.17,4.89,6.32,5.93,6.97,4.62,5.09,4.61,5.76,7.48,5.33,6.86,6.29,7.74,4.30,6.64,1963-08-31
2,-2.06,-2.39,-1.65,0.03,-0.91,-2.68,0.02,-0.54,-3.18,-0.89,1.90,0.75,-3.44,-2.54,-2.83,0.42,-2.40,1963-09-30
3,0.38,1.38,2.66,5.97,5.77,3.81,1.95,1.86,3.80,8.80,0.33,6.57,4.50,3.66,3.98,1.99,1.74,1963-10-31
4,-0.85,-0.80,0.32,-3.63,-1.17,0.57,2.30,0.28,0.38,-4.99,-0.70,-1.27,-1.01,-0.53,1.80,2.81,-0.92,1963-11-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,9.03,8.64,12.58,9.07,3.37,6.39,1.70,11.51,13.58,9.62,8.76,9.63,1.11,7.07,5.75,-3.43,9.17,2022-10-31
712,5.75,10.05,6.00,5.49,6.14,3.42,-3.35,6.54,5.50,2.99,6.92,6.91,5.84,4.21,2.67,-3.91,-2.63,2022-11-30
713,-5.60,-2.18,-4.07,-4.63,-6.15,-8.25,-13.85,-3.94,-4.19,-4.59,-4.66,-4.29,-6.88,-9.39,-7.15,-19.16,-7.07,2022-12-31
714,5.52,3.16,4.63,5.10,11.43,13.00,15.54,3.15,6.02,8.26,3.33,1.71,15.35,14.29,11.78,21.09,9.33,2023-01-31
715,-2.03,-6.03,-3.51,-2.95,-2.31,-1.52,0.25,-3.14,-3.85,-3.45,-2.66,-3.97,-1.72,-1.87,-1.19,4.41,-4.92,2023-02-28