In [70]:
import pandas as pd
from pandas.tseries.offsets import MonthEnd

In [71]:
# crsp = pd.read_feather('crsp_monthly.ftr')
# crsp

In [72]:
industry_ret = pd.read_csv('49_Industry_Portfolios.CSV', skiprows=1, nrows=1160, index_col=0)
industry_ret['caldt'] = pd.to_datetime(industry_ret.index, format='%Y%m', errors='coerce') + MonthEnd(0)
industry_ret = industry_ret.query("caldt >= '1963-07-31'")
industry_ret = industry_ret.reset_index(drop=True)
industry_ret['InNoVaTiOn'] = industry_ret['Softw'] + industry_ret['Telcm'] + industry_ret['ElcEq'] \
                           - industry_ret['Guns'] - industry_ret['Gold'] - industry_ret['Mines']
industry_ret

,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,Clths,...,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fins,Other,caldt,InNoVaTiOn
0,3.04,-0.46,2.57,-2.19,-2.54,-5.07,-0.70,-0.07,-0.15,-0.67,...,0.14,-1.08,-4.21,-1.58,-1.74,-4.48,1.62,3.67,1963-07-31,-93.98
1,-0.32,4.73,5.50,2.14,7.15,5.03,7.84,5.28,6.22,4.83,...,4.21,6.65,1.07,4.15,2.90,3.44,5.45,9.77,1963-08-31,-101.82
2,-1.94,-1.53,-0.90,1.23,-4.23,-5.15,-2.26,2.98,-1.37,-4.04,...,-1.65,1.13,-2.51,-3.11,-1.36,-4.05,-4.24,2.85,1963-09-30,-90.21
3,-0.13,2.69,1.10,-1.28,5.78,15.66,1.96,-1.99,4.25,2.51,...,1.43,0.45,1.11,-1.30,1.54,4.85,1.38,3.46,1963-10-31,-103.11
4,-3.06,-0.39,-0.58,-0.72,-5.63,-0.83,-3.97,-0.62,-0.18,-1.44,...,-4.01,-1.09,-3.61,-3.31,-4.19,-4.88,-0.03,0.70,1963-11-30,-100.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,13.79,11.12,7.13,9.49,12.08,5.48,14.98,8.82,5.68,10.72,...,13.65,1.94,10.26,13.54,12.83,6.82,11.34,10.48,2022-10-31,-21.86
712,2.53,2.84,7.69,3.23,5.57,9.79,7.24,15.70,9.44,17.34,...,5.05,2.95,5.65,5.19,1.41,10.88,8.30,7.11,2022-11-30,-19.85
713,-12.14,-2.39,-0.41,-4.15,1.87,-8.17,-5.40,-7.77,0.77,-0.33,...,-5.63,-8.97,-6.82,-6.38,-3.21,-6.56,-6.49,-3.27,2022-12-31,-15.88
714,10.00,-2.10,-2.61,-3.57,1.46,13.87,19.42,11.49,-0.36,9.23,...,6.89,10.92,10.48,9.51,-0.34,16.30,8.40,1.79,2023-01-31,8.65
715,-3.35,-1.13,-2.64,0.20,-3.36,-5.28,-4.24,-4.60,-2.74,-5.97,...,-0.33,-5.51,-1.98,-1.98,-3.58,-2.29,-2.20,-2.31,2023-02-28,13.85

In [73]:
ep_ret = pd.read_csv('Portfolios_Formed_on_E-P.CSV', skiprows=17, nrows=860, index_col=0)
ep_ret['caldt'] = pd.to_datetime(ep_ret.index, format='%Y%m', errors='coerce') + MonthEnd(0)
ep_ret = ep_ret.query("caldt >= '1963-07-31'")
ep_ret = ep_ret.reset_index(drop=True)
ep_ret['EP_HML'] = ep_ret['Hi 10'] - ep_ret['Lo 10']
ep_ret

,<= 0,Lo 30,Med 40,Hi 30,Lo 20,Qnt 2,Qnt 3,Qnt 4,Hi 20,Lo 10,...,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Hi 10,caldt,EP_HML
0,1.51,-0.33,0.22,0.92,-0.54,0.06,0.60,1.09,-0.34,-0.16,...,0.56,-0.53,1.36,-0.71,-0.54,1.57,-0.27,-0.42,1963-07-31,-0.26
1,7.73,5.38,4.77,6.05,5.14,5.88,4.53,5.62,6.72,5.75,...,6.41,5.25,3.93,5.58,5.29,5.72,7.32,5.99,1963-08-31,0.24
2,-5.73,-0.41,-2.09,-1.55,0.01,-1.95,-2.44,-1.34,-1.66,-0.22,...,-2.18,-1.67,-2.85,-1.72,-0.81,-1.50,-1.26,-2.15,1963-09-30,-1.93
3,4.19,3.78,0.36,6.53,4.05,1.32,0.44,6.79,2.82,4.91,...,2.63,-0.25,0.13,0.96,1.14,8.40,3.96,1.43,1963-10-31,-3.48
4,-1.23,0.94,-0.89,-3.91,1.28,-0.84,-0.90,-4.21,-0.96,-0.57,...,-0.52,-1.24,-0.10,-2.25,-0.06,-5.32,-1.87,0.19,1963-11-30,0.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,6.20,5.21,9.40,14.47,3.52,9.47,7.18,15.41,13.23,4.19,...,8.39,10.81,3.46,13.54,14.95,15.70,13.18,13.35,2022-10-31,9.16
712,1.48,4.01,6.61,5.73,4.44,4.39,7.24,5.51,6.37,2.64,...,3.21,5.82,7.73,6.47,6.15,5.10,5.90,7.41,2022-11-30,4.77
713,-6.32,-7.67,-4.40,-5.42,-8.52,-5.08,-5.04,-4.41,-5.68,-12.82,...,-6.11,-3.87,-6.38,-2.93,-3.22,-5.16,-4.89,-7.39,2022-12-31,5.43
714,13.03,9.00,3.52,7.25,10.63,4.23,4.94,4.80,7.69,17.14,...,6.10,2.05,5.55,4.02,1.69,6.81,5.75,12.06,2023-01-31,-5.08
715,-1.45,-1.20,-3.13,-3.15,-0.99,-2.16,-2.99,-3.94,-2.66,3.15,...,-1.60,-2.84,-3.34,-2.44,-4.43,-3.64,-2.66,-2.68,2023-02-28,-5.83

In [74]:
inv_ret = pd.read_csv('Portfolios_Formed_on_INV.CSV', skiprows=17, nrows=716, index_col=0)
inv_ret['caldt'] = pd.to_datetime(inv_ret.index, format='%Y%m', errors='coerce') + MonthEnd(0)
inv_ret = inv_ret.query("caldt >= '1963-07-31'")
inv_ret = inv_ret.reset_index(drop=True)
inv_ret['INV_HML'] = inv_ret['Hi 10'] - inv_ret['Lo 10']
inv_ret

,Lo 30,Med 40,Hi 30,Lo 20,Qnt 2,Qnt 3,Qnt 4,Hi 20,Lo 10,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Hi 10,caldt,INV_HML
0,-1.14,0.32,0.43,-1.61,-0.11,0.60,0.27,0.55,-2.34,-0.69,-0.12,-0.10,1.04,0.25,0.25,0.30,0.49,0.73,1963-07-31,3.07
1,5.84,5.02,5.54,6.07,5.35,5.45,4.53,6.47,5.40,6.90,5.34,5.36,5.64,5.30,4.54,4.51,6.05,7.72,1963-08-31,2.32
2,-1.43,-1.09,-1.08,-0.62,-1.39,-2.44,-0.48,-1.33,-0.83,-0.37,-3.21,-0.32,-2.76,-2.18,-0.26,-0.80,-1.15,-1.85,1963-09-30,-1.02
3,2.28,1.70,5.98,2.66,0.93,1.32,3.22,7.39,2.91,2.37,1.41,0.66,0.95,1.61,2.41,4.41,8.41,4.38,1963-10-31,1.47
4,0.39,0.02,-2.04,0.74,-1.12,-1.42,0.88,-3.47,1.85,-0.62,-0.40,-1.53,-1.80,-1.11,1.77,-0.40,-4.39,-0.64,1963-11-30,-2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,12.84,8.59,4.24,12.59,12.91,8.01,5.91,4.65,11.92,13.13,13.04,12.78,5.59,9.17,7.18,3.56,2.25,7.72,2022-10-31,-4.20
712,5.80,5.56,3.54,6.58,4.95,3.95,6.24,3.82,7.34,5.97,5.19,4.70,6.74,2.65,7.90,3.06,3.40,4.34,2022-11-30,-3.00
713,-3.46,-5.72,-8.51,-3.39,-3.65,-6.03,-7.31,-8.05,-3.07,-3.66,-3.51,-3.79,-2.79,-7.59,-6.33,-9.28,-7.58,-8.61,2022-12-31,-5.54
714,3.74,5.87,11.50,3.95,4.66,5.85,7.34,12.25,7.03,1.47,3.58,5.79,5.05,6.25,5.95,10.23,11.23,13.48,2023-01-31,6.45
715,-2.90,-2.26,-1.62,-2.48,-3.08,-1.54,-1.85,-2.52,-3.42,-1.68,-3.24,-2.92,-1.71,-1.46,-2.74,-0.08,-4.80,0.18,2023-02-28,3.60

In [75]:
op_ret = pd.read_csv('Portfolios_Formed_on_OP.CSV', skiprows=24, nrows=726, index_col=0)
op_ret['caldt'] = pd.to_datetime(op_ret.index, format='%Y%m', errors='coerce') + MonthEnd(0)
op_ret = op_ret.query("caldt >= '1963-07-31'")
op_ret = op_ret.reset_index(drop=True)
op_ret['OP_HML'] = pd.to_numeric(op_ret['Hi 10']) - pd.to_numeric(op_ret['Lo 10'])
op_ret

,Lo 30,Med 40,Hi 30,Lo 20,Qnt 2,Qnt 3,Qnt 4,Hi 20,Lo 10,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Hi 10,caldt,OP_HML
0,-0.84,0.44,0.00,-0.65,1.10,-0.12,-0.99,0.53,-1.44,-0.19,-1.02,2.19,-0.84,0.92,-0.72,-1.15,-0.31,0.98,1963-07-31,2.42
1,5.44,4.90,5.81,4.84,4.36,5.41,5.44,6.01,5.53,4.45,6.00,3.55,5.62,5.11,5.57,5.36,5.90,6.07,1963-08-31,0.54
2,-1.63,-0.85,-1.44,-2.15,-2.11,0.53,-1.78,-1.48,-3.02,-1.65,-1.15,-2.59,2.21,-1.88,-2.48,-1.34,-2.48,-0.97,1963-09-30,2.05
3,0.90,1.48,5.86,0.82,0.30,2.38,2.65,6.86,0.77,0.85,0.97,-0.05,3.41,0.84,0.98,3.67,2.92,8.88,1963-10-31,8.11
4,-1.44,0.27,-1.35,-1.04,-1.03,0.99,0.39,-2.41,0.18,-1.74,-1.81,-0.63,2.05,-0.63,-0.74,1.06,0.30,-3.73,1963-11-30,-3.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,1.37,1.17,1.83,1.50,0.82,1.16,1.48,2.07,2.15,0.52,0.99,0.65,1.48,0.79,1.78,1.18,2.58,1.74,1963-10-31,-0.41
720,-2.12,-0.93,-1.88,-2.46,-0.50,-1.46,-0.90,-2.24,-3.27,-1.26,-1.12,0.11,-1.60,-1.30,-0.94,-0.87,-0.92,-3.11,1963-11-30,0.16
721,-1.02,0.67,-0.10,-1.24,0.23,0.42,0.66,-0.24,-2.32,0.37,-0.36,0.81,-0.54,1.49,1.04,0.29,0.77,-0.90,1963-12-31,1.42
722,4.24,2.81,2.73,5.02,3.04,2.10,2.13,3.23,5.52,4.28,1.96,4.10,2.57,1.57,2.91,1.36,2.23,3.88,1964-01-31,-1.64
723,3.03,1.73,1.96,3.52,1.97,1.74,1.06,2.30,3.87,2.99,1.63,2.30,2.37,1.03,1.11,1.02,3.00,1.85,1964-02-29,-2.02

In [76]:
url = 'http://diether.org/prephd/10-port_mom_ew.csv'
port = pd.read_csv(url,parse_dates=['caldt'])
port

          caldt         p0         p1         p2        p3        p4
0    1927-01-31  -2.708397   4.290747   0.776512  1.210773  0.508464
1    1927-02-28   5.418420   8.356758   4.758203  4.905527  5.422874
2    1927-03-31  -3.829973  -2.910900  -1.801945  0.259834  0.020529
3    1927-04-30  -0.747539  -0.438827  -0.216951 -0.172500  3.216826
4    1927-05-31   3.314240   5.759958   7.950440  8.014930  8.587076
...         ...        ...        ...        ...       ...       ...
1144 2022-05-31  -5.392614  -2.553349   0.502323 -0.183222  1.199527
1145 2022-06-30  -5.344633  -8.743887  -8.291228 -4.778448 -9.131728
1146 2022-07-29  11.776372  11.033183   9.284861  6.875124  8.193744
1147 2022-08-31   0.317134  -2.100848  -2.140245 -2.222316  0.123339
1148 2022-09-30 -10.184062 -10.091326 -10.592417 -5.988948 -8.171841

[1149 rows x 6 columns]

In [77]:
df = pd.merge(pd.merge(pd.merge(pd.merge(port, industry_ret, on='caldt'), inv_ret[['caldt', 'INV_HML']], on = 'caldt'),ep_ret[['caldt', 'EP_HML']], on = 'caldt'), op_ret[['caldt', 'OP_HML']], on = 'caldt')
df

,caldt,p0,p1,p2,p3,p4,Agric,Food,Soda,Beer,...,Meals,Banks,Insur,RlEst,Fins,Other,InNoVaTiOn,INV_HML,EP_HML,OP_HML
0,1963-07-31,-1.643322,-1.284810,-0.512732,-0.979859,-0.385561,3.04,-0.46,2.57,-2.19,...,-4.21,-1.58,-1.74,-4.48,1.62,3.67,-93.98,3.07,-0.26,2.42
1,1963-07-31,-1.643322,-1.284810,-0.512732,-0.979859,-0.385561,3.04,-0.46,2.57,-2.19,...,-4.21,-1.58,-1.74,-4.48,1.62,3.67,-93.98,3.07,-0.26,1.31
2,1963-09-30,-2.617577,-0.725381,-1.154537,-1.158321,-1.688062,-1.94,-1.53,-0.90,1.23,...,-2.51,-3.11,-1.36,-4.05,-4.24,2.85,-90.21,-1.02,-1.93,2.05
3,1963-09-30,-2.617577,-0.725381,-1.154537,-1.158321,-1.688062,-1.94,-1.53,-0.90,1.23,...,-2.51,-3.11,-1.36,-4.05,-4.24,2.85,-90.21,-1.02,-1.93,-1.68
4,1963-10-31,0.322188,0.710325,0.512692,1.902940,3.337489,-0.13,2.69,1.10,-1.28,...,1.11,-1.30,1.54,4.85,1.38,3.46,-103.11,1.47,-3.48,8.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,2022-03-31,-0.062720,-0.159941,0.989489,1.019774,2.040128,10.78,1.27,-0.67,3.34,...,0.85,-4.67,6.40,-1.81,-0.11,8.55,-27.05,-3.51,-5.98,-0.03
497,2022-05-31,-5.392614,-2.553349,0.502323,-0.183222,1.199527,7.29,-3.26,-0.22,-1.60,...,-3.29,3.41,1.14,-2.34,3.95,-1.44,11.11,-13.96,7.99,8.83
498,2022-06-30,-5.344633,-8.743887,-8.291228,-4.778448,-9.131728,-12.45,-1.91,0.46,-0.02,...,-9.02,-12.39,-2.06,-13.60,-9.79,-12.67,11.12,10.19,-0.46,3.12
499,2022-08-31,0.317134,-2.100848,-2.140245,-2.222316,0.123339,5.23,-0.46,-4.40,-1.87,...,-1.47,-3.41,-0.84,-6.12,-1.02,-4.04,-1.81,-2.85,4.23,-8.18
500,2022-09-30,-10.184062,-10.091326,-10.592417,-5.988948,-8.171841,-7.03,-7.65,-8.14,-5.21,...,-6.26,-9.21,-4.45,-12.89,-8.47,-5.95,-23.11,-0.96,-3.94,-1.61

In [79]:
from statsmodels.formula.api import ols
ols('p4 ~ 1 + INV_HML + EP_HML + OP_HML + InNoVaTiOn', data = df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     p4   R-squared:                       0.326
Model:                            OLS   Adj. R-squared:                  0.320
Method:                 Least Squares   F-statistic:                     59.84
Date:                Thu, 06 Apr 2023   Prob (F-statistic):           3.15e-41
Time:                        13:48:18   Log-Likelihood:                -1540.7
No. Observations:                 501   AIC:                             3091.
Df Residuals:                     496   BIC:                             3112.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.8796      0.240      7.841      0.000       1.409       2.351
INV_HML        0.2914      0.075      3.894      0.000       0.144       0.438
EP_HML         0.0974      0.058      1.671      0.095      -0.017       0.212
OP_HML        -0.8041      0.055    -14.535      0.000      -0.913      -0.695
InNoVaTiOn     0.0130      0.009      1.490      0.137      -0.004       0.030
==============================================================================
Omnibus:                       26.923   Durbin-Watson:                   1.955
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.292
Skew:                          -0.340   Prob(JB):                     1.20e-11
Kurtosis:                       4.395   Cond. No.                         28.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""